### ISSUE TITLE
panic: The specified module could not be found in xbox one cmd

### ISSUE THREAD

**Issue by PurpleVoidEpic** [yuk7/ArchWSL#312]
**the issue**
the bug:

goroutine 1 [running]:
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20220128215802-99c3d69c2c27/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20220128215802-99c3d69c2c27/windows/dll_windows.go:333
github.com/yuk7/wsllib-go._WslLaunch(0xc00000eae0, 0xc00000eaa8, 0xc00000ea01, 0x184, 0x18c, 0x190,
0xc00010fe58, 0x0, 0xc00001a930)
        C:/Users/runneradmin/go/pkg/mod/github.com/yuk7/wsllib-go@v1.0.0/zsyscall_windows.go:78 +0x19f
github.com/yuk7/wsllib-go.WslLaunch(0xc000012438, 0x4, 0x0, 0x0, 0x100000001, 0x184, 0x18c, 0x190, 0x0, 0xf6090a, ...)
        C:/Users/runneradmin/go/pkg/mod/github.com/yuk7/wsllib-go@v1.0.0/wsllib.go:66 +0xed
github.com/yuk7/wsllib-go.WslLaunchInteractive(0xc000012438, 0x4, 0x0, 0x0, 0x40000000001, 0xc000000000, 0xc00010ff20, 0xf900f1)
        C:/Users/runneradmin/go/pkg/mod/github.com/yuk7/wsllib-go@v1.0.0/wsllib.go:81 +0x1b7
github.com/yuk7/wsldl/run.Execute(0xc000012438, 0x4, 0xc0000423c0, 0x0, 0x0)
        D:/a/wsldl/wsldl/src/run/execute.go:23 +0x133
main.main()
        D:/a/wsldl/wsldl/src/main.go:36 +0x165

**Expected behavior**
To work perfectly fine without any panic errors

**Screenshots**

**Enviroment:**
 - Microsoft Windows [Version 10.0.22621.3422] on xbox one dev mode cmd
 - Security Software: None
 - WSL version 1 possibly i just found out the xbox one had wsl.exe in system32
 - ArchWSL version im using the latest version
 - Im using the ArchWSL arch.exe
 - wsldl2, version 22020900  (amd64)
**Additional context**
Hi im new please help me im trying to run linux on my xbox one via the cmd via ssh I know xbox one is not compatible but I heard the is like portable wsl without admin so im getting an error please help

**Comment by lllsondowlll** [comment]
It's a symlink to an unmounted drive H:\. It requires an XVD containing the Xbox build of WSL included. As far as I know neither WSL2 nor WSL.exe is included in System.
