### ISSUE TITLE
Missing implementation of get_mempolicy and NUMA support

### ISSUE THREAD

**Issue by andradei** [yuk7/ArchWSL#344]
`ps` command uncovers the lack of the C method `get_mempolicy` in the system.

So the error message on the screenshot below appears everytime `ps` is ran. If another program uses `get_mempolicy` internally, it will display the same error.

**To Reproduce**
Run `ps` command

**Expected behavior**
Don't show error:

`get_mempolicy: Function not implemented`

**Screenshots**
![image](https://github.com/yuk7/ArchWSL/assets/2653546/8d53a738-5b58-4de9-867a-0ba90db61fc5)

**Enviroment:**
 - Microsoft Windows [Version 10.0.22621.3007]
 - Webroot
 - WSL2
 - ArchWSL 20.10.16.0
 - ArchWSL Installer type: `scoop install extras/archwsl`
 - Launcher version: 22020900

**Comment by librehugohu** [comment]
Similar question. My error message seems caused by powershell.

![image](https://github.com/yuk7/ArchWSL/assets/51823222/e4c650e5-21cf-4787-8ed6-627b6b57cdd2)

**Comment by damienbutt** [comment]
I am also getting this on all of my Arch installs. 

For me, it seems to be the `eval "$(fnm env --use-on-cd)"` call at the end of my `.zshrc`. This is for Fast Node Manager.

If I comment that line out the problem goes away.

**Comment by sirianni** [comment]
I just started getting this also.  For me, I can reproduce it using `ps`

```
$ ps
get_mempolicy: Function not implemented
    PID TTY          TIME CMD
    582 pts/0    00:00:00 zsh
   4528 pts/0    00:00:00 ps
```

**Comment by maple3142** [comment]
I temporarily solved this by downgrading `numactl` to `2.0.16-1` and prevent it from upgrading. (Add `numactl` to `IgnorePkg` in `/etc/pacman.conf`)

**Comment by andradei** [comment]
So is this something that will "solve itself" when `ps`, `fnm` and others get updated to support newer versions on `numactl`?

**Comment by sirianni** [comment]
> So is this something that will "solve itself" when `ps`, `fnm` and others get updated to support newer versions on `numactl`?

No.  I think the issue is that the kernel for ArchWSL does not have NUMA enabled.

**Comment by maple3142** [comment]
`numactl` version 2.0.18-1 has fixed this issue by removing the warning message (https://github.com/numactl/numactl/issues/212), so it is fine to unpin it and do an upgrade normally.

> No. I think the issue is that the kernel for ArchWSL does not have NUMA enabled.
But ArchWSL doesn't provide an kernel at all. The default kernel used in WSL2 is compiled and provided by Microsoft, and they don't have NUMA enabled by default.

**Comment by jjtmp** [comment]
@maple3142 It doesn't resolve my similar issue on OpenSUSE where an invocation of /usr/bin/ps produces the error message in /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c numa_get_mems_allowed().

GDB backtrace (partially): 
```
#17 0xb7a5f663 in numa_error (where=0xb7a66725 "get_mempolicy")
    at /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c:282
#18 0xb7a63fd7 in numa_get_mems_allowed ()
    at /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c:1308
#19 0xb7a5fea9 in set_kernel_abi ()
    at /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c:632
#20 set_sizes () at /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c:662
#21 numa_init () at /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c:103
#22 numa_init () at /usr/src/debug/numactl-2.0.19.14.g690a72c/libnuma.c:96
#23 0xb7fce31c in call_init (l=<optimized out>, argc=1, argv=0xbfffeb74, 
    env=0x443770) at dl-init.c:74
#24 call_init (l=<optimized out>, argc=1, argv=0xbfffeb74, env=0x443770)
    at dl-init.c:26
```
